# Generated by Django 5.2.5 on 2025-09-15 09:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedVideo',
            fields=[
                ('video_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('file_path', models.CharField(max_length=512)),
                ('thumbnail_path', models.CharField(blank=True, max_length=512, null=True)),
                ('suggestions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('provider', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedShort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('short_path', models.CharField(max_length=512)),
                ('thumbnail_path', models.CharField(max_length=512)),
                ('start_time', models.CharField(max_length=12)),
                ('end_time', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('social_title', models.CharField(blank=True, max_length=255, null=True)),
                ('social_description', models.TextField(blank=True, null=True)),
                ('social_hashtags', models.JSONField(blank=True, default=list, null=True)),
                ('parent_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='shorts_app.downloadedvideo')),
            ],
        ),
    ]
