# Generated by Django 5.2.5 on 2025-08-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_app', '0007_alter_videoclip_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedshort',
            name='social_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedshort',
            name='social_hashtags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='generatedshort',
            name='social_title',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
    ]
