# Generated by Django 5.2.5 on 2025-08-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_app', '0008_generatedshort_social_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedshort',
            name='social_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
